### PR TITLE
Add&Fix some CHS-translation

### PR DESCRIPTION
**Pull request by AnnaKutou**
There are many Chinses are using your Rev, so I copy this file from my fork. Some differents, but it still works^_^

### CODE REVIEW

**Comment by bombless** [comment]
愉♂悦

**Comment by xiuluo** [comment]
愉♂悦什么鬼。。

**Comment by Astrologers** [comment]
对齐的位置又乱了（。。。
English lang does not correspond to the order of items
Modification is not conducive to the future
Sorry my not very good at English

**Comment by yuyuvn** [comment]
a random english comment

**Comment by AnnaKutou** [comment]
......Maybe, Item words were NOT kept in line. Sorry I can't understand clearly, too.QAQ
请好好用中文再表述一下吧...

**Pull request merged**
