### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by gakada**

### CODE REVIEW

**Comment by gakada** [comment]
I see you updated them yourself. Can you comment on
- Jun'you vs Junyou
- Standardizing 改二 for ship and equipment names
- boss sink vs S rank for quest 279

**Comment by yuyuvn** [comment]
according to wiki, Q 279 don't need S rank, it only request you sink the flagship
I prefer Junyou than Jun'you
standardizing 改二 is good, thanks

**Comment by gakada** [comment]
You mean [wikiwiki](http://wikiwiki.jp/kancolle/?%C7%A4%CC%B3)? It says S rank. In the [comments](http://wikiwiki.jp/kancolle/?%C7%A4%CC%B3%2F%A5%B3%A5%E1%A5%F3%A5%C812) there is this:

```
北方ケ号作戦「再」突入、敵旗艦撃沈せずのA勝利では未達成。敵旗艦撃沈またはS勝利が必要な模様 -- 2015-07-18 (土) 00:42:02
    ↑再挑戦してS勝利で達成。敵旗艦を撃沈してのA勝利(随伴艦撃ち洩らし)で達成になるかどうかは不明 -- 2015-07-18 (土) 00:54:45
    ダメコン戦法で大破進撃したから夜戦に行くか迷ったが、正解だったようだなあ -- 2015-07-18 (土) 01:59:51　　以下ツリー化
    「第一水雷戦隊」北方ケ号作戦、再突入！は５隻撃沈ではクリアできなかったのでS勝利限定っぽいです -- 2015-07-19 (日) 00:02:38 New
    旗艦は撃沈したのですか？？ -- 2015-07-19 (日) 01:24:58 New
    「第一水雷戦隊」北方ケ号作戦、再突入！　旗艦含む4隻撃沈A勝利で未達成 -- 2015-07-19 (日) 05:15:13 New
        続き　S勝利で達成　表を書き換え -- 2015-07-19 (日) 06:36:41 New
    「第一水雷戦隊」北方ケ号作戦、再突入！」　旗艦含む5隻撃沈で未達成 -- 2015-07-19 (日) 05:57:09 New
```

Jun'you seems like a right romanization (https://en.wikipedia.org/wiki/Romanization_of_Japanese, all variants use んよ -> n'yo, https://en.wikipedia.org/wiki/Hepburn_romanization#Syllabic_n, "to avoid confusion between, for example, んあ n + a and な na, and んや n + ya and にゃ nya", https://en.wikipedia.org/wiki/Japanese_aircraft_carrier_Jun%27y%C5%8D), unless you just want it sans apostrophe.

**Comment by gakada** [comment]
Also, when a ship name is in quest description, should it be with untranslated name, e.g.

```
Have Souryuu Kai2 (蒼龍改二) as flagship
```

or just

```
Have Souryuu Kai2 as flagship
```

**Comment by yuyuvn** [comment]
Add untranslated name should be good to find ship for new player

**Pull request closed without merging**
